names=Fail,Raise
visibility=public
kind=defined

--- Raise(exception_class = nil, *rest) -> ()
--- Fail(exception_class = nil, *rest)  -> ()
登録されている情報を使用して、例外を発生させます。

@param exception_class 例外クラス。

@param rest メッセージに埋め込む値。

@raise Exception2MessageMapper::ErrNotRegisteredException 指定された例外クラスに対応するメッセージが存在しない場合に発生します。

例:

  class Foo
    extend Exception2MessageMapper
    p def_exception :NewExceptionClass, "message...%d, %d and %d" # =>
    
    def foo
      Raise NewExceptionClass, 1, 2, 3
    end
  end
  
  Foo.new().foo() #=> in `Raise': message...1, 2 and 3 (Foo::NewExceptionClass)
                  #   という例外が発生します。
  
  Foo.Raise Foo::NewExceptionClass, 1, 3, 5  #=> in `Raise': message...1, 3 and 5 (Foo::NewExceptionClass)
                                             #   という例外が発生します。

